##########################################################################################
# targets/target_xml_cache_support.py
##########################################################################################
"""The target context product index is stored in `caches/TARGET_XML_CACHE/$LOOKUP.pickle`.
This pickle file contains a single dictionary keyed by `title`, every `alternate_title`,
and `logical identifier`. Small bodies are also keyed by any of their standard
designations, whether or not they appear in the XML file as an `alternate_title`. Keys
appear in their given case and also in upper case.

The dictionary returns the basename of the most recent version of the context XML file.

The committed cache is a read-only mirror of the Engineering Node (latest versions only).
It can be supplemented by "_local" files generated by `new_target_xml_dict` and
`update_target_xml_dict`. So the committed cache is never dirtied by these writers (e.g.
during testing), `use_local_xml_dir()` activates an overlay directory (the hard-wired,
gitignored `caches/TARGET_XML_OVERLAY` by default): within that context "_local" files and
the effective, merged `$LOOKUP.pickle` are written to the overlay, reads resolve
overlay-first, and the committed cache is left untouched.
"""

import contextlib
import datetime
import pathlib
import pickle
import re
import textwrap
from xml.sax.saxutils import escape

import anyascii
import lxml.etree
import requests
from pdslogger import PdsLogger, NullLogger
from pdstemplate import PdsTemplate

from targets._DISALLOWED_MINOR_PLANET_NAMES import _DISALLOWED_MINOR_PLANET_NAMES
from targets.remote_listdir import remote_listdir
from targets.targettype import TargetType

_TARGET_URL = 'https://pds.nasa.gov/data/pds4/context-pds4/target/'
_TARGET_XML_CACHE = pathlib.Path(__file__).parents[2] / 'caches/TARGET_XML_CACHE'
_TARGET_LOOKUP_BASENAME = '$LOOKUP.pickle'

# The committed cache above is a read-only mirror of the Engineering Node (latest versions
# only) plus its $LOOKUP.pickle. When an overlay directory is activated via
# use_local_xml_dir(), all "_local" files and the effective (merged) lookup pickle are
# written there instead, leaving the committed cache pristine; reads resolve
# overlay-first. The overlay is hard-wired to caches/TARGET_XML_OVERLAY (gitignored, so it
# is never committed); it is the default target of use_local_xml_dir(). _LOCAL_XML_DIR is
# the active overlay, or None to disable it so that everything resolves to the committed
# cache.
_TARGET_XML_OVERLAY = _TARGET_XML_CACHE.parent / 'TARGET_XML_OVERLAY'
_LOCAL_XML_DIR: pathlib.Path | None = None

_BASENAME_SPLITTER = re.compile(r'(.*)_(\d)\.(\d)(|_local)\.xml$')
_XMLNS = re.compile(r'\s*(?:xmlns|xsi)(?:|:\w+)\s*=\s*"[^"]+"')

_TARGET_XML_LOOKUP = None   # filled in lazily

_TEMPLATE_BASENAME = 'TARGET_LABEL_1.0.xml'
# Inside the package, so it is found in an installed copy as well as a source checkout.
_TEMPLATE_PATH = pathlib.Path(__file__).parent / 'templates' / _TEMPLATE_BASENAME
_PDS_TEMPLATE = None        # filled in lazily


##########################################################################################
# Directory resolution: committed cache plus an optional writable overlay
##########################################################################################


def _search_dirs() -> list[pathlib.Path]:
    """The directories to search for XML files and the lookup pickle, overlay first."""

    if _LOCAL_XML_DIR is not None:
        return [_LOCAL_XML_DIR, _TARGET_XML_CACHE]
    return [_TARGET_XML_CACHE]


def _write_dir() -> pathlib.Path:
    """The directory that receives new "_local" files and the rebuilt lookup pickle: the
    overlay when active, otherwise the committed cache."""

    return _LOCAL_XML_DIR if _LOCAL_XML_DIR is not None else _TARGET_XML_CACHE


def _lookup_path() -> pathlib.Path:
    """The path of the effective lookup pickle: the overlay's copy when the overlay is
    active and has one, otherwise the committed cache's copy."""

    if _LOCAL_XML_DIR is not None:
        local = _LOCAL_XML_DIR / _TARGET_LOOKUP_BASENAME
        if local.exists():
            return local
    return _TARGET_XML_CACHE / _TARGET_LOOKUP_BASENAME


def _find_xml(basename: str) -> pathlib.Path | None:
    """The full path of an XML basename, searching the overlay first and then the
    committed cache. None if it is in neither directory."""

    for directory in _search_dirs():
        path = directory / basename
        if path.exists():
            return path
    return None


@contextlib.contextmanager
def use_local_xml_dir(path: str | pathlib.Path | None = _TARGET_XML_OVERLAY):
    """Temporarily route "_local" writes and the effective lookup to an overlay directory.

    Within the context, `new_target_xml_dict`/`update_target_xml_dict` write their
    "_local.xml" files into `path`, `_update_target_cache` writes the merged
    `$LOOKUP.pickle` there, and reads resolve overlay-first; the committed
    `TARGET_XML_CACHE` is never modified. The previous configuration and cached lookup are
    restored on exit, so the context nests cleanly and is safe per-test under `pytest -n
    auto`.

    Parameters:
        path: The overlay directory (created if necessary); defaults to the hard-wired,
            gitignored `caches/TARGET_XML_OVERLAY`. Pass None to disable the overlay.
    """

    global _LOCAL_XML_DIR, _TARGET_XML_LOOKUP

    prev_dir = _LOCAL_XML_DIR
    prev_lookup = _TARGET_XML_LOOKUP
    if path is not None:
        path = pathlib.Path(path)
        path.mkdir(parents=True, exist_ok=True)
    _LOCAL_XML_DIR = path
    _TARGET_XML_LOOKUP = None    # force a reload against the new configuration
    try:
        yield
    finally:
        _LOCAL_XML_DIR = prev_dir
        _TARGET_XML_LOOKUP = prev_lookup


##########################################################################################
# Reading the cache
##########################################################################################


def target_xml_lookup() -> dict:
    """The target lookup dictionary, which returns a file path given a name, alias, or
    lid.
    """

    global _TARGET_XML_LOOKUP

    if _TARGET_XML_LOOKUP is None:
        with open(_lookup_path(), 'rb') as f:
            _TARGET_XML_LOOKUP = pickle.load(f)

    return _TARGET_XML_LOOKUP


def target_xml_path(key: str) -> dict | None:
    """Return the XML path for the lookup key.

    Parameters:
        key: Any key defining the body, as found in the `$LOOKUP` dictionary.

    Returns:
        A Path if the key is found; None otherwise.
    """

    try:
        basename = target_xml_lookup()[key.upper()]
    except KeyError:
        return None

    return _find_xml(basename)


def target_xml_dict(key: str) -> dict | None:
    """Return a target dictionary containing the core content of a target XML file.

    Parameters:
        key: Any key defining the body, as found in the `$LOOKUP` dictionary.

    Returns:
        A dictionary containing keys "lid", "lid_tail", "version_id", "title",
        "alt_titles", "type_name", "ttype", "description", and "xml_path". None if there
        is no existing XML file for this body.
    """

    xml_path = target_xml_path(key)
    return _read_target_xml_dict(xml_path) if xml_path is not None else None


def _read_target_xml_dict(xml_path: str | pathlib.Path) -> dict | None:
    """Return a target dictionary containing the core content of a target XML file.

    Parameters:
        xml_path: Path to the XML file.

    Returns:
        A dictionary containing keys "lid", "lid_tail", "version_id", "title",
        "alt_titles", "type_name", "ttype", "description", and "xml_path". None if there
        is no existing XML file for this body.
    """

    xml_path = pathlib.Path(xml_path)
    content = pathlib.Path(xml_path).read_text()
    content = content.rpartition('?>')[-1].lstrip()
    content = ''.join(_XMLNS.split(content))
    tree = lxml.etree.fromstring(content)

    target_dict = {
        'lid': tree.xpath('//logical_identifier')[0].text,
        'version_id': tree.xpath('//version_id')[0].text,
        'title': tree.xpath('//title')[0].text,
        'alt_titles': [node.text for node in tree.xpath('//alternate_title')],
        'type_name': tree.xpath('//type')[-1].text,
        'xml_path': xml_path,
    }

    target_dict['full_name'] = target_dict['title']
    target_dict['lid_tail'] = target_dict['lid'].rpartition(':')[-1]
    target_dict['ttype'] = TargetType.LOOKUP[target_dict['type_name']]

    desc = tree.xpath('//description')[-1].text
    if not desc or desc.lower() in ('none', 'none.'):
        target_dict['description'] = []
    else:
        desc = [line.strip() for line in desc.split('\n')]
        target_dict['description'] = [line for line in desc if line]

    return target_dict


def find_xml_path(body_dict: dict) -> dict | None:
    """Return the path to an existing XML context product for a body defined by the given
    dict.

    Returns None if the body is not found.
    """

    options = []
    for key in ('lid_tail', 'title', 'full_name'):
        if key in body_dict:
            options.append(body_dict[key].upper())
    for key in ('alt_titles', 'aliases', 'lookups'):
        if key in body_dict:
            options += [k.upper() for k in body_dict[key]]

    for key in options:
        xml_path = target_xml_path(key)
        if xml_path:
            return xml_path

    return None


def find_xml_dict(body_dict: dict) -> dict | None:
    """Return the content of an XML context product for a body defined by the given dict.

    Returns None if the body is not found.
    """

    xml_path = find_xml_path(body_dict)
    return _read_target_xml_dict(xml_path) if xml_path is not None else None


##########################################################################################
# Cache management
##########################################################################################


def _update_target_cache(*, logger: PdsLogger | None = None,
                         rebuild: bool = False,
                         offline: bool = False,
                         warn_on_duplicates: bool = True):
    """Update the target cache.

    Parameters:
        logger: Logger to use.
        rebuild: True to rebuild the index even if no files have changed.
        offline: True to prevent a check of the Engineering Node; this option can be used
            to add a "_local" file and/or rebuild the cache without Internet access.
        warn_on_duplicates: True to issue a warning about duplicate aliases; False to
            suppress these warnings.
    """

    if offline:
        rebuild = True

    # Check the local context products
    logger and logger.info(f'Checking local targets: {_TARGET_XML_CACHE}')
    local_basenames = {p.name for p in _TARGET_XML_CACHE.iterdir()}
    local_basenames.discard(_TARGET_LOOKUP_BASENAME)

    if not offline:
        # Get the list of remote XML files
        logger and logger.info(f'Checking remote targets: {_TARGET_URL}')
        remote_info = remote_listdir(_TARGET_URL, logger=logger, verbose=False)
        remote_basenames = sorted(t[0] for t in remote_info)

        # Merge the lists of local and remote basenames
        merged_basenames = set(local_basenames) | set(remote_basenames)

        # Identify and retrieve the latest versions
        latest_basenames = _latest_basenames(merged_basenames)

        updates = 0
        for basename in latest_basenames:
            if basename in local_basenames:
                continue

            # Retrieve remote content
            url = _TARGET_URL + basename
            logger and logger.info('Retrieving', basename)
            try:
                request = requests.get(url, allow_redirects=True, timeout=60)
            except requests.RequestException as err:
                logger and logger.error(f'Unable to retrieve {basename}: {err}')
                continue

            if request.status_code == 200:
                # Save this file to the cache
                (_TARGET_XML_CACHE / basename).write_bytes(request.content)
                updates += 1
            else:
                logger and logger.error(f'Response {request.status_code} received',
                                        basename)

        # Remove local copies of old versions
        local_basenames = [p.name for p in _TARGET_XML_CACHE.iterdir()]
        local_basenames.sort()

        latest_basenames = set(_latest_basenames(local_basenames))
        for basename in local_basenames:
            if basename.endswith('.xml') and basename not in latest_basenames:
                logger and logger.debug('Superseded file removed', basename)
                (_TARGET_XML_CACHE / basename).unlink()

        # Summarize local updates
        for basename in local_basenames:
            if (basename.endswith('_local.xml')
                    and (_TARGET_XML_CACHE / basename).exists()):
                logger and logger.info('Local update retained', basename)

        if not updates:
            logger and logger.info('Target cache is up to date')

        if not (updates or rebuild):
            logger and logger.blankline()
            return

    # (offline falls straight through to the rebuild)

    # Re-index...
    logger and logger.info('Rebuilding target cache index', _TARGET_LOOKUP_BASENAME)

    # Gather the latest version of every target across the committed cache and the overlay
    # (overlay first, so a "_local" file wins a tie). paths[basename] -> full path.
    paths = {}
    for directory in _search_dirs():
        if not directory.is_dir():      # a gitignored overlay may not exist yet
            continue
        for path in directory.iterdir():
            if path.name.endswith('.xml') and path.name not in paths:
                paths[path.name] = path

    # lookup_by_name[title, alias, or lid] -> context file basename
    # ambiguous keys are removed
    lookup = {}
    duplicates = set()
    for basename in _latest_basenames(list(paths)):
        body_dict = _read_target_xml_dict(paths[basename])
        keys = _lookup_keys(body_dict, logger=logger)
        for key in keys:
            if key in lookup:
                duplicates.add(key)
                if warn_on_duplicates:
                    logger and logger.warning(f'Duplicate key "{key}" ignored: '
                                              f'{lookup[key]}, {basename}')
            else:
                lookup[key] = basename

    for key in duplicates:
        del lookup[key]

    # Add uppercase versions of all keys
    lookup.update({key.upper(): value for key, value in lookup.items()})

    # Save the dictionary as a pickle file
    _write_target_xml_lookup(lookup)
    logger and logger.info('Index rebuilt', _TARGET_LOOKUP_BASENAME)


def _latest_basenames(basenames: list[str] | set[str]) -> str:
    """Filter out all but the latest version of each target context file.

    Also remove any "collection_target" files, which can appear in the online directory.
    """

    # Remove "collection_target" files, deprecated files, and anything not ending in .xml
    basenames = [b for b in basenames if b.endswith('.xml')]
    basenames = [b for b in basenames if not b.endswith('_deprecated.xml')]
    basenames = [b for b in basenames if not b.startswith('collection_target')]
    basenames = [b for b in basenames if not b.startswith('Collection_target')]

    # Example basename: dwarf_planet.136108_haumea_1.2.xml
    version_dict = {}
    for basename in basenames:
        lid = _BASENAME_SPLITTER.match(basename).group(1)
        version_dict.setdefault(lid, []).append(basename)

    latest = []
    for version_list in version_dict.values():
        version_list.sort(key=_sort_key)
        latest.append(version_list[-1])

    latest.sort()   # return in alphabetical order
    return latest


# MPNAME: Matches a name including diacritics, apostrophes and internal dashes; no digits
# or spaces. Note that "[^\W\d_]" only matches letters but they can have diacritics.
# Dashes cannot appear at the beginning or end.
_MPNAME = r"(?:[^\W\d_]|['`]){3,}"  # at least 3 letters

# Comet names can have spaces but no punctuation at end
_CNAME = r"(?:[^\W\d_]|['`])(?:[^\W\d_]|['` -])*(?:[^\W\d_])"

_MP_NUMBER_DESIG = re.compile(r'\((\d+)\) ([12]\d\d\d [A-HJ-Y][A-HJ-Z]\d*)$')
_MP_NUMBER_SURVEY = re.compile(r'\((\d+)\) (\d\d\d\d (?:P-L|T-[123]))$')
_MP_NUMBER_NAME = re.compile(rf'\(?(\d+)\)? ({_MPNAME})$')

_C_PREFIX_NAME_FRAG = re.compile(rf'(\d+[CPDXI])/{_CNAME}(?: \d+|)(-[A-Z][A-Z]?\d*)$')
_C_NAME = re.compile(rf'{_CNAME}(?: \d+|)(-[A-Z][A-Z]?\d*)$')

_INVALID_STAR = re.compile(r'[JSUN]\d+', re.I)


def _lookup_keys(body_dict: dict, logger: PdsLogger | None = None) -> set[str]:

    old_keys = set([body_dict['title'], body_dict['lid_tail']] + body_dict['alt_titles'])
    new_keys = old_keys.copy()

    if body_dict['ttype'] in TargetType.MCODES:
        # Split number from name or designation
        for key in old_keys:
            for regex in (_MP_NUMBER_DESIG, _MP_NUMBER_SURVEY, _MP_NUMBER_NAME):
                match = regex.match(key)
                if match:
                    new_keys |= set(match.groups())
                    break

        new_keys = {k for k in new_keys if k not in _DISALLOWED_MINOR_PLANET_NAMES}

    elif body_dict['ttype'] == TargetType.COMET:
        # Append fragment to designation if name intervenes
        for key in old_keys:
            match = _C_PREFIX_NAME_FRAG.match(key)
            if match:
                new_keys.add(match.group(1) + '-' + match.group(2))

    new_keys |= {anyascii.anyascii(key).replace('`', "'") for key in new_keys}

    # Deconflict star "U28" from moon "U28"
    if body_dict['ttype'] not in TargetType.PLANETARY_CODES:
        alt_new_keys = set()
        for key in new_keys:
            if _INVALID_STAR.fullmatch(key):
                type_name = TargetType.NAME[body_dict['ttype']]
                logger and logger.debug(f'Ignoring {type_name} alias {key}')
            else:
                alt_new_keys.add(key)
        new_keys = alt_new_keys

    return new_keys


def _write_target_xml_lookup(lookup: dict):
    """Write the target context lookup dictionary."""

    global _TARGET_XML_LOOKUP

    with open(_write_dir() / _TARGET_LOOKUP_BASENAME, 'wb') as f:
        pickle.dump(lookup, f)

    _TARGET_XML_LOOKUP = lookup


def _sort_key(basename):
    """Guarantees that basenames sort by increasing version even for x.9 -> x.10, and that
    "_local.xml" comes before ".xml".
    """

    match = _BASENAME_SPLITTER.match(basename)
    return (match.group(1), match.group(2), match.group(3), 0 if match.group(4) else 1)


##########################################################################################
# Target XML writers
##########################################################################################

def new_target_xml_dict(body_dict: dict, logger: PdsLogger | None = None) -> pathlib.Path:
    """Write a new target XML file into the cache; update the lookup.

    Returns the path to the new file.
    """

    global _PDS_TEMPLATE

    basename = f'{body_dict["lid_tail"]}_1.0_local.xml'
    logger and logger.info('Writing new target context file: ', basename)
    if _PDS_TEMPLATE is None:
        PdsTemplate.set_logger(logger or NullLogger())
        _PDS_TEMPLATE = PdsTemplate(_TEMPLATE_PATH, xml=True, crlf=False)

    xml_path = _write_dir() / basename
    if xml_path.exists():
        raise FileExistsError(f'File {xml_path} already exists')

    # The template refers to the body as `target`, so the dictionary is nested under that
    # key rather than passed as the top-level namespace.
    _PDS_TEMPLATE.write({'target': body_dict}, xml_path, raise_exceptions=True)
    _update_target_cache(offline=True, warn_on_duplicates=False)    # update the lookup
    return xml_path


_TARGET_TITLE = re.compile(r'(.*<title>)'
                           r'(.*?)'
                           r'(</title>.*<Target>.*<name>)'
                           r'(.*?)'
                           r'(</name>.*)', re.DOTALL)

_ALT_TITLE = re.compile(r'(.*\n)'
                        r'(\s*<Alias>\s*<alternate_title>)'
                        r'(.*?)'
                        r'(</alternate_title>\s*</Alias>\s*\n)'
                        r'(.*)', re.DOTALL)

_ALT_TITLE2 = re.compile(r'(.*?</product_class>\s*\n)'  # if Alias_List is absent
                         r'(\s*?)'
                         r'(<Modification_History>.*)', re.DOTALL)

_TARGET_TYPE = re.compile(r'(.*<Target>.*<type>)'
                          r'(.*?)'
                          r'(</type>.*)', re.DOTALL)

_DESCRIPTION = re.compile(r'(.*\s<Target>.*\n)'
                          r'(\s*)<description>'  # indent = the spaces before <desc>
                          r'(.*?)'
                          r'(</description>.*)', re.DOTALL)

_MOD_DETAIL = re.compile(r'(.*?\n)'
                         r'(\s*<Modification_Detail>\s*<modification_date>)'
                         r'(.*?)'
                         r'(</modification_date>\s*<version_id>)'
                         r'(\d+)\.(\d+)'
                         r'(</version_id>\s*\n)'
                         r'(\s*)<description>'  # indent = the spaces before <desc>
                         r'(.*?)'
                         r'(</description>\s*</Modification_Detail>\s*\n)'
                         r'(.*)', re.DOTALL)

_VERSION_ID = re.compile(r'(.*?\n\s*<version_id>)'
                         r'(\d+)\.(\d+)'
                         r'(.*)', re.DOTALL)


def update_target_xml_dict(body_dict: dict, logger: PdsLogger | None = None):
    """Write a new local XML file with updated information, if any.

    Parameters:
        body_dict: The new body dictionary.
        logger: Logger to use.

    Returns:
        pathlib.Path or None: The Path to the new file if it was modified, with a version
        number incremented by 0.1. If no change is required, the path to the pre-existing
        XML file is returned.

    Raises:
        FileNotFoundError: If the XML file does not exist.
        FileExistsError: Upon attempting to write an XML file that already exists.
    """

    # Get the current body content
    xml_path = find_xml_path(body_dict)
    if xml_path is None:
        raise FileNotFoundError(f'XML file not found for {body_dict["lid_tail"]}')

    content = xml_path.read_text()
    xml_dict = _read_target_xml_dict(xml_path)
    changes = []

    # Warn about a LID change, but only if the old LID is not an option among the new
    # aliases.
    compatible = _compatible_lids(body_dict, xml_dict)  # might update body_dict's LID
    new_lid = body_dict['lid_tail']
    old_lid = xml_dict['lid_tail']
    if new_lid != old_lid:
        if compatible:
            logger and logger.info(f'Deprecated LID: "{old_lid}" ought to be "{new_lid}"')
        else:
            logger and logger.warning(f'LID mismatch: new="{new_lid}"; '
                                      f'original="{old_lid}" (retained)')

    # Update the title
    new_test = body_dict['title'].replace('(', '').replace(')', '').upper()
    old_test = xml_dict['title'].replace('(', '').replace(')', '').upper()
    new_aliases = _missing_aliases(body_dict, xml_dict)
    if new_test != old_test:
        title = body_dict['title']
        logger and logger.info(f'Replacing title: "{title}"')
        match = _TARGET_TITLE.match(content)
        (before, old_title, mid1, _, mid2) = match.groups()
        new_content = [before, title, mid1, title, mid2]
        content = ''.join(new_content)
        if old_title not in new_aliases:
            new_aliases = [old_title] + new_aliases
        if title in new_aliases:
            new_aliases.remove(title)
        changes.append(f'revised title (was "{old_title}")')

    # Insert the new alt_titles
    if new_aliases:
        logger and logger.info(f'Inserting new aliases: {new_aliases}')
        match = _ALT_TITLE.match(content)
        if match:
            (before, mid1, last_alt_title, mid2, after) = match.groups()
            new_content = [before, mid1, last_alt_title, mid2]
            for alt in new_aliases:
                new_content += [mid1, escape(alt), mid2]
            new_content += [after]
        else:
            match = _ALT_TITLE2.match(content)
            (before, indent, after) = match.groups()
            new_content = [before, indent, '<Alias_List>\n']
            for alt in new_aliases:
                new_content += [indent, '  <Alias>\n', indent, '    <alternate_title>',
                                escape(alt), '</alternate_title>\n', indent,
                                '  </Alias>\n']
            new_content += [indent, '</Alias_List>\n', indent, after]
        content = ''.join(new_content)
        plural = 's' if len(new_aliases) > 1 else ''
        changes.append(f'additional alt_title{plural}')

    # Update the target type
    if body_dict['ttype'] != xml_dict['ttype']:
        logger and logger.info(f'Replacing type: {body_dict["type_name"]}')
        match = _TARGET_TYPE.match(content)
        (before, old_type, after) = match.groups()
        new_content = [before, body_dict['type_name'], after]
        content = ''.join(new_content)
        changes.append(f'revised type (was "{old_type}")')

    # Fill in or expand the Target description
    new_desc = _new_desc(body_dict, xml_dict)
    if new_desc:
        match = _DESCRIPTION.match(content)
        (before, indent, old_desc, after) = match.groups()
        preserve_old = old_desc.lower().strip() not in ('', 'none', 'none.')
        logger and logger.info(('Expanding' if preserve_old else 'Inserting')
                               + ' target description')
        new_content = [before, indent, '<description>\n']
        if preserve_old:
            desc = [line.strip() for line in old_desc.split()]
        else:
            desc = []
        desc += body_dict['description']
        for line in desc:
            new_content += [indent, '  ', escape(line), '\n']
        new_content += [indent, after]
        content = ''.join(new_content)
        changes.append(('expanded' if preserve_old else 'new') + ' description')

    # If nothing has changed, return the path to the exiting file
    if not changes:
        return xml_path

    # Modification_Detail description
    new_desc = "Updated by the RMS Node's HST pipeline: " + ', '.join(changes) + '.'
    if new_lid != old_lid:
        new_desc += ' Note that the logical_identifier has not been modified.'

    match = _MOD_DETAIL.match(content)
    (before, mid1, mod_date, mid2,
     v1, v2, mid3, indent, old_desc, mid4, after) = match.groups()
    new_version = f'{v1}.{int(v2) + 1}'
    new_desc = '\n'.join(textwrap.wrap(new_desc, width=(90 - len(indent) - 2),
                                       initial_indent=indent + '  ',
                                       subsequent_indent=indent + '  '))
    new_content = [before,
                   mid1, datetime.date.today().isoformat(),
                   mid2, new_version,
                   mid3, indent, '<description>\n', new_desc, '\n', indent,
                   mid4,
                   mid1, mod_date, mid2, v1, '.', v2, mid3, indent, '<description>',
                   old_desc, mid4, after]
    content = ''.join(new_content)

    # Update the version_id
    match = _VERSION_ID.match(content)
    (before, v1, v2, after) = match.groups()
    new_content = [before, new_version, after]
    content = ''.join(new_content)

    # Write the new file into the overlay (or the committed cache when no overlay is
    # active). Note that this reuses the existing LID, even if the LID has changed.
    new_basename = xml_path.name.replace('_local.xml', '.xml')
    new_basename = new_basename.replace(f'{v1}.{v2}.xml', f'{new_version}_local.xml')
    new_path = _write_dir() / new_basename
    if new_path.exists():
        raise FileExistsError(f'File {new_path} already exists')

    new_path.write_text(content)
    _update_target_cache(offline=True, warn_on_duplicates=False)    # update the lookup
    return new_path


# Pattern that matches any minor planet or comet LID name that is based on a designation,
# ignoring any target type, planet name, or minor planet number.
_LID_DESIG = re.compile(r'(?:.*\.)?(?:\d+_)?'
                        r'((?:[pcdxa])?\d\d\d\d_(?:[a-z][a-z]?\d*|p-l|t-\d))$')


def _compatible_lids(target, reference):
    """True if one of the various possible target LIDs for the given `target` is
    consistent with the LID of the `reference`.

    As a side effect, if `target`'s LID is based on a temporary designation, select the
    `title` among its `alt_title`s that use the same designation as `reference`'s LID.

    Parameters:
        target (dict): Target body dictionary.
        reference (dict): Reference body dictionary.

    Returns:
        True if the LIDs are the compatible, even if not exactly the same.
    """

    def lid_desig(lid):
        """The part of the LID that is based on a temporary designation, if any."""
        match = _LID_DESIG.fullmatch(lid)
        return match.group(1) if match else ''

    target_lid = target['lid_tail']
    reference_lid = reference['lid_tail']

    # Match must be exact if `target` is not a small body
    if target['ttype'] not in TargetType.SMALL_BODY_CODES:
        return target_lid == reference_lid

    # Target type must be an exact match
    if target['ttype'] != reference['ttype']:
        return False

    # If the name is the same except for a leading mnum, it's a match
    mnum = target.get('mnum')
    if mnum and target_lid.endswith(reference_lid.partition('.')[-1]):
        return True

    # If the reference LID involves a designation and the target uses the same designation
    # as a title or alt_title, they are compatible
    reference_desig = lid_desig(reference_lid)
    if reference_desig:
        test_titles = [target['title']] + target['alt_titles']
        for k, test_title in enumerate(test_titles):
            test_desig = lid_desig(_lid_name(target, alt_title=test_title))
            if test_desig == reference_desig:

                # Favor this LID if the new target is also using a temporary designation
                target_desig = lid_desig(target_lid)
                if target_desig and k > 0:
                    title = target['title']
                    target['alt_titles'].pop(k-1)
                    # Shuffle the minor planet numbers between the titles
                    if mnum:
                        prefix = f'({mnum}) '
                        if not test_title.startswith(prefix):
                            test_title = prefix + test_title
                        if title.startswith(prefix):
                            title = title.replace(prefix, '')

                    if title not in target['alt_titles']:
                        target['alt_titles'].append(title)
                    target['title'] = test_title
                    target['lid_tail'] = _lid_tail(target, alt_title=test_title)

                return True

    return False


def _lid_tail(target, *, alt_title=''):
    """The LID of the target following the colon, depending on `title` and `ttype`.

    Specify `alt_title` to override the target's `title`.
    """

    lid_name = _lid_name(target, alt_title=alt_title)
    type_name = TargetType.NAME[target['ttype']].replace(' ', '_').lower()
    return type_name + '.' + lid_name


def _lid_name(target, *, alt_title=''):
    """The LID of the target following the target's type.

    Specify `alt_title` to build the LID from a different name than the default.
    """

    name = alt_title or target.get('lid_name') or target['full_name']
    name = anyascii.anyascii(name).lower()

    # Slashes are handled inconsistently in comets!
    if name[1] == '/':
        name = name.replace('/', '')    # C/2007 N3 -> C2007 N3
    else:
        name = name.replace('/', ' ')   # 1P/Halley -> 1P Halley

    # Filter out disallowed characters
    name = name.replace(' ', '_').lower()
    name = ''.join(c for c in name if c in 'abcdefghijklmnopqrstuvwxyz0123456789_-.:')
    return name


def _missing_aliases(new_body, old_body):
    """Titles of the new body that do not appear in the old body's list of titles, either
    as a string or a substring.

    Returns the list of extra names.
    """

    new_names = [new_body['title']] + new_body['alt_titles']
    old_names = set([old_body['title']] + old_body['alt_titles'])
    extras = []
    minor_planet_number = ''
    for name in new_names:
        if name in old_names:
            continue

        # Omit a new name entirely inside an old name
        inside = False
        for test in old_names:
            if name in test:
                inside = True
                break
        if inside:
            continue

        # Omit "Minor Planet ..."
        if name.startswith('Minor Planet'):
            minor_planet_number = name  # don't force an update just for this
            continue

        # Omit a name that is the same except for parentheses
        match = False
        for test in old_names:
            test = test.replace('(', '').replace(')', '')
            name2 = name.replace('(', '').replace(')', '')
            if test == name2:
                match = True
                break
        if match:
            continue

        extras.append(name)

    if extras and minor_planet_number:
        extras.append(minor_planet_number)

    return extras


def _new_desc(new_body, old_body):
    """True if none of the new body's description appears in the old body's description.
    """

    if not new_body['description']:
        return False

    # Compare ignoring spaces and case
    old_desc = {d.replace(' ', '').lower() for d in old_body['description']}

    for text in new_body['description']:
        text = text.replace(' ', '').lower()
        if text and text in old_desc:
            return False

    return True


__all__ = [
    'find_xml_dict',
    'find_xml_path',
    'new_target_xml_dict',
    'target_xml_dict',
    'target_xml_lookup',
    'target_xml_path',
    'update_target_xml_dict',
    'use_local_xml_dir',
]

##########################################################################################
