##########################################################################################
# targets/target_xml_cache_support.py
##########################################################################################
"""The target context product index is stored in `caches/TARGET_XML_CACHE/$LOOKUP.pickle`.
This pickle file contains a single dictionary keyed by `title`, every `alternate_title`,
and `logical identifier`. Small bodies are also keyed by any of their standard
designations, whether or not they appear in the XML file as an `alternate_title`. Keys
appear in their given case and also in upper case.

The dictionary returns the basename of the most recent version of the context XML file.

The committed cache is a read-only mirror of the Engineering Node (latest versions only).
It can be supplemented by "_local" files generated by `new_target_xml_dict` and
`update_target_xml_dict`. So the committed cache is never dirtied by these writers (e.g.
during testing), `use_local_xml_dir()` activates an overlay directory (the hard-wired,
gitignored `caches/TARGET_XML_OVERLAY` by default): within that context "_local" files and
the effective, merged `$LOOKUP.pickle` are written to the overlay, reads resolve
overlay-first, and the committed cache is left untouched.
"""

import contextlib
import datetime
import pathlib
import pickle
import re
from xml.sax.saxutils import escape

import anyascii
import lxml.etree
import requests
from pdslogger import PdsLogger, NullLogger
from pdstemplate import PdsTemplate

from targets._DISALLOWED_MINOR_PLANET_NAMES import _DISALLOWED_MINOR_PLANET_NAMES
from targets.remote_listdir import remote_listdir
from targets.targettype import TargetType

_TARGET_URL = 'https://pds.nasa.gov/data/pds4/context-pds4/target/'
_TARGET_XML_CACHE = pathlib.Path(__file__).parent.parent / 'caches/TARGET_XML_CACHE'
_TARGET_LOOKUP_BASENAME = '$LOOKUP.pickle'

# The committed cache above is a read-only mirror of the Engineering Node (latest versions
# only) plus its $LOOKUP.pickle. When an overlay directory is activated via
# use_local_xml_dir(), all "_local" files and the effective (merged) lookup pickle are
# written there instead, leaving the committed cache pristine; reads resolve
# overlay-first. The overlay is hard-wired to caches/TARGET_XML_OVERLAY (gitignored, so it
# is never committed); it is the default target of use_local_xml_dir(). _LOCAL_XML_DIR is
# the active overlay, or None to disable it so that everything resolves to the committed
# cache.
_TARGET_XML_OVERLAY = _TARGET_XML_CACHE.parent / 'TARGET_XML_OVERLAY'
_LOCAL_XML_DIR: pathlib.Path | None = None

_BASENAME_SPLITTER = re.compile(r'(.*)_(\d)\.(\d)(|_local)\.xml$')
_XMLNS = re.compile(r'\s*(?:xmlns|xsi)(?:|:\w+)\s*=\s*"[^"]+"')

_TARGET_XML_LOOKUP = None   # filled in lazily

_TEMPLATE_BASENAME = 'TARGET_LABEL_1.0.xml'
_TEMPLATE_PATH = pathlib.Path(__file__).parent.parent / 'templates' / _TEMPLATE_BASENAME
_PDS_TEMPLATE = None        # filled in lazily


##########################################################################################
# Directory resolution: committed cache plus an optional writable overlay
##########################################################################################


def _search_dirs() -> list[pathlib.Path]:
    """The directories to search for XML files and the lookup pickle, overlay first."""

    if _LOCAL_XML_DIR is not None:
        return [_LOCAL_XML_DIR, _TARGET_XML_CACHE]
    return [_TARGET_XML_CACHE]


def _write_dir() -> pathlib.Path:
    """The directory that receives new "_local" files and the rebuilt lookup pickle: the
    overlay when active, otherwise the committed cache."""

    return _LOCAL_XML_DIR if _LOCAL_XML_DIR is not None else _TARGET_XML_CACHE


def _lookup_path() -> pathlib.Path:
    """The path of the effective lookup pickle: the overlay's copy when the overlay is
    active and has one, otherwise the committed cache's copy."""

    if _LOCAL_XML_DIR is not None:
        local = _LOCAL_XML_DIR / _TARGET_LOOKUP_BASENAME
        if local.exists():
            return local
    return _TARGET_XML_CACHE / _TARGET_LOOKUP_BASENAME


def _find_xml(basename: str) -> pathlib.Path | None:
    """The full path of an XML basename, searching the overlay first and then the
    committed cache. None if it is in neither directory."""

    for directory in _search_dirs():
        path = directory / basename
        if path.exists():
            return path
    return None


@contextlib.contextmanager
def use_local_xml_dir(path: str | pathlib.Path | None = _TARGET_XML_OVERLAY):
    """Temporarily route "_local" writes and the effective lookup to an overlay directory.

    Within the context, `new_target_xml_dict`/`update_target_xml_dict` write their
    "_local.xml" files into `path`, `_update_target_cache` writes the merged
    `$LOOKUP.pickle` there, and reads resolve overlay-first; the committed
    `TARGET_XML_CACHE` is never modified. The previous configuration and cached lookup are
    restored on exit, so the context nests cleanly and is safe per-test under
    `pytest -n auto`.

    Parameters:
        path: The overlay directory (created if necessary); defaults to the hard-wired,
            gitignored `caches/TARGET_XML_OVERLAY`. Pass None to disable the overlay.
    """

    global _LOCAL_XML_DIR, _TARGET_XML_LOOKUP

    prev_dir = _LOCAL_XML_DIR
    prev_lookup = _TARGET_XML_LOOKUP
    if path is not None:
        path = pathlib.Path(path)
        path.mkdir(parents=True, exist_ok=True)
    _LOCAL_XML_DIR = path
    _TARGET_XML_LOOKUP = None    # force a reload against the new configuration
    try:
        yield
    finally:
        _LOCAL_XML_DIR = prev_dir
        _TARGET_XML_LOOKUP = prev_lookup


##########################################################################################
# Reading the cache
##########################################################################################


def target_xml_lookup() -> dict:
    """The target lookup dictionary, which returns a file path given a name, alias, or
    lid.
    """

    global _TARGET_XML_LOOKUP

    if _TARGET_XML_LOOKUP is None:
        with open(_lookup_path(), 'rb') as f:
            _TARGET_XML_LOOKUP = pickle.load(f)

    return _TARGET_XML_LOOKUP


def target_xml_path(key: str) -> dict | None:
    """Return the XML path for the lookup key.

    Parameters:
        key: Any key defining the body, as found in the `$LOOKUP` dictionary.

    Returns:
        A Path if the key is found; None otherwise.
    """

    try:
        basename = target_xml_lookup()[key.upper()]
    except KeyError:
        return None

    return _find_xml(basename)


def target_xml_dict(key: str) -> dict | None:
    """Return a target dictionary containing the core content of a target XML file.

    Parameters:
        key: Any key defining the body, as found in the `$LOOKUP` dictionary.

    Returns:
        A dictionary containing keys "lid", "lid_tail", "version_id", "title",
        "alt_titles", "type_name", "ttype", "description", and "xml_path". None if there
        is no existing XML file for this body.
    """

    xml_path = target_xml_path(key)
    return _read_target_xml_dict(xml_path) if xml_path is not None else None


def _read_target_xml_dict(xml_path: str | pathlib.Path) -> dict | None:
    """Return a target dictionary containing the core content of a target XML file.

    Parameters:
        xml_path: Path to the XML file.

    Returns:
        A dictionary containing keys "lid", "lid_tail", "version_id", "title",
        "alt_titles", "type_name", "ttype", "description", and "xml_path". None if there
        is no existing XML file for this body.
    """

    xml_path = pathlib.Path(xml_path)
    content = pathlib.Path(xml_path).read_text()
    content = content.rpartition('?>')[-1].lstrip()
    content = ''.join(_XMLNS.split(content))
    tree = lxml.etree.fromstring(content)

    target_dict = {
        'lid': tree.xpath('//logical_identifier')[0].text,
        'version_id': tree.xpath('//version_id')[0].text,
        'title': tree.xpath('//title')[0].text,
        'alt_titles': [node.text for node in tree.xpath('//alternate_title')],
        'type_name': tree.xpath('//type')[-1].text,
        'xml_path': xml_path,
    }

    target_dict['lid_tail'] = target_dict['lid'].rpartition(':')[-1]
    target_dict['ttype'] = TargetType.LOOKUP[target_dict['type_name']]

    desc = tree.xpath('//description')[-1].text
    if not desc or desc.lower() in ('none', 'none.'):
        target_dict['description'] = []
    else:
        desc = [line.strip() for line in desc.split('\n')]
        target_dict['description'] = [line for line in desc if line]

    return target_dict


def find_xml_path(body_dict: dict) -> dict | None:
    """Return the path to an existing XML context product for a body defined by the given
    dict.

    Returns None if the body is not found.
    """

    options = []
    for key in ('lid_tail', 'title', 'full_name'):
        if key in body_dict:
            options.append(body_dict[key].upper())
    for key in ('alt_titles', 'aliases', 'lookups'):
        if key in body_dict:
            options += [k.upper() for k in body_dict[key]]

    for key in options:
        xml_path = target_xml_path(key)
        if xml_path:
            return xml_path

    return None


def find_xml_dict(body_dict: dict) -> dict | None:
    """Return the content of an XML context product for a body defined by the given dict.

    Returns None if the body is not found.
    """

    xml_path = find_xml_path(body_dict)
    return _read_target_xml_dict(xml_path) if xml_path is not None else None


##########################################################################################
# Cache management
##########################################################################################


def _update_target_cache(*, logger: PdsLogger | None = None,
                         rebuild: bool = False,
                         offline: bool = False,
                         warn_on_duplicates: bool = True):
    """Update the target cache.

    Parameters:
        logger: Logger to use.
        rebuild: True to rebuild the index even if no files have changed.
        offline: True to prevent a check of the Engineering Node; this option can be used
            to add a "_local" file and/or rebuild the cache without Internet access.
        warn_on_duplicates: True to issue a warning about duplicate aliases; False to
            suppress these warnings.
    """

    if offline:
        rebuild = True

    # Check the local context products
    logger and logger.info(f'Checking local targets: {_TARGET_XML_CACHE}')
    local_basenames = set(p.name for p in _TARGET_XML_CACHE.iterdir())
    local_basenames.discard(_TARGET_LOOKUP_BASENAME)

    if not offline:
        # Get the list of remote XML files
        logger and logger.info(f'Checking remote targets: {_TARGET_URL}')
        remote_info = remote_listdir(_TARGET_URL, logger=logger, verbose=False)
        remote_basenames = sorted(t[0] for t in remote_info)

        # Merge the lists of local and remote basenames
        merged_basenames = set(local_basenames) | set(remote_basenames)

        # Identify and retrieve the latest versions
        latest_basenames = _latest_basenames(merged_basenames)

        updates = 0
        for basename in latest_basenames:
            if basename in local_basenames:
                continue

            # Retrieve remote content
            url = _TARGET_URL + basename
            logger and logger.info('Retrieving', basename)
            try:
                request = requests.get(url, allow_redirects=True, timeout=60)
            except requests.RequestException as err:
                logger and logger.error(f'Unable to retrieve {basename}: {err}')
                continue

            if request.status_code == 200:
                # Save this file to the cache
                (_TARGET_XML_CACHE / basename).write_bytes(request.content)
                updates += 1
            else:
                logger and logger.error(f'Response {request.status_code} received',
                                        basename)

        # Remove local copies of old versions
        local_basenames = [p.name for p in _TARGET_XML_CACHE.iterdir()]
        local_basenames.sort()

        latest_basenames = set(_latest_basenames(local_basenames))
        for basename in local_basenames:
            if basename.endswith('.xml') and basename not in latest_basenames:
                logger and logger.debug('Superseded file removed', basename)
                (_TARGET_XML_CACHE / basename).unlink()

        # Summarize local updates
        for basename in local_basenames:
            if (basename.endswith('_local.xml')
                    and (_TARGET_XML_CACHE / basename).exists()):
                logger and logger.info('Local update retained', basename)

        if not updates:
            logger and logger.info('Target cache is up to date')

        if not (updates or rebuild):
            logger and logger.blankline()
            return

    # (offline falls straight through to the rebuild)

    # Re-index...
    logger and logger.info('Rebuilding target cache index', _TARGET_LOOKUP_BASENAME)

    # Gather the latest version of every target across the committed cache and the overlay
    # (overlay first, so a "_local" file wins a tie). paths[basename] -> full path.
    paths = {}
    for directory in _search_dirs():
        if not directory.is_dir():      # a gitignored overlay may not exist yet
            continue
        for path in directory.iterdir():
            if path.name.endswith('.xml') and path.name not in paths:
                paths[path.name] = path

    # lookup_by_name[title, alias, or lid] -> context file basename
    # ambiguous keys are removed
    lookup = {}
    duplicates = set()
    for basename in _latest_basenames(list(paths)):
        body_dict = _read_target_xml_dict(paths[basename])
        keys = _lookup_keys(body_dict)
        for key in keys:
            if key in lookup:
                duplicates.add(key)
                if warn_on_duplicates:
                    logger.warning(f'Duplicate key "{key}" ignored: {lookup[key]}, '
                                   f'{basename}')
            else:
                lookup[key] = basename

    for key in duplicates:
        del lookup[key]

    # Add uppercase versions of all keys
    lookup.update({key.upper(): value for key, value in lookup.items()})

    # Save the dictionary as a pickle file
    _write_target_xml_lookup(lookup)
    logger and logger.info('Index rebuilt', _TARGET_LOOKUP_BASENAME)


def _latest_basenames(basenames: list[str] | set[str]) -> str:
    """Filter out all but the latest version of each target context file.

    Also remove any "collection_target" files, which can appear in the online directory.
    """

    # Remove "collection_target" files, deprecated files, and anything not ending in .xml
    basenames = [b for b in basenames if b.endswith('.xml')]
    basenames = [b for b in basenames if not b.endswith('_deprecated.xml')]
    basenames = [b for b in basenames if not b.startswith('collection_target')]
    basenames = [b for b in basenames if not b.startswith('Collection_target')]

    # Example basename: dwarf_planet.136108_haumea_1.2.xml
    version_dict = {}
    for basename in basenames:
        lid = _BASENAME_SPLITTER.match(basename).group(1)
        version_dict.setdefault(lid, []).append(basename)

    latest = []
    for lid, version_list in version_dict.items():
        version_list.sort(key=_sort_key)
        latest.append(version_list[-1])

    latest.sort()   # return in alphabetical order
    return latest


# MPNAME: Matches a name including diacritics, apostrophes and internal dashes; no digits
# or spaces. Note that "[^\W\d_]" only matches letters but they can have diacritics.
# Dashes cannot appear at the beginning or end.
_MPNAME = r"(?:[^\W\d_]|['`]){3,}"  # at least 3 letters

# Comet names can have spaces but no punctuation at end
_CNAME = r"(?:[^\W\d_]|['`])(?:[^\W\d_]|['` -])*(?:[^\W\d_])"

_MP_NUMBER_DESIG = re.compile(r'\((\d+)\) ([12]\d\d\d [A-HJ-Y][A-HJ-Z]\d*)$')
_MP_NUMBER_SURVEY = re.compile(r'\((\d+)\) (\d\d\d\d (?:P-L|T-[123]))$')
_MP_NUMBER_NAME = re.compile(rf'\(?(\d+)\)? ({_MPNAME})$')

_C_PREFIX_NAME_FRAG = re.compile(rf'(\d+[CPDXI])/{_CNAME}(?: \d+|)(-[A-Z][A-Z]?\d*)$')
_C_NAME = re.compile(rf'{_CNAME}(?: \d+|)(-[A-Z][A-Z]?\d*)$')


def _lookup_keys(body_dict: dict) -> list[str]:

    old_keys = set([body_dict['title'], body_dict['lid_tail']] + body_dict['alt_titles'])
    new_keys = old_keys.copy()

    if body_dict['ttype'] in TargetType.MCODES:
        # Split number from name or designation
        for key in old_keys:
            for regex in (_MP_NUMBER_DESIG, _MP_NUMBER_SURVEY, _MP_NUMBER_NAME):
                match = regex.match(key)
                if match:
                    new_keys |= set(match.groups())
                    break

        new_keys = {k for k in new_keys if k not in _DISALLOWED_MINOR_PLANET_NAMES}

    elif body_dict['ttype'] == TargetType.COMET:
        # Append fragment to designation if name intervenes
        for key in old_keys:
            match = _C_PREFIX_NAME_FRAG.match(key)
            if match:
                new_keys.add(match.group(1) + '-' + match.group(2))

    new_keys |= {anyascii.anyascii(key).replace('`', "'") for key in new_keys}
    return new_keys


def _write_target_xml_lookup(lookup: dict):
    """Write the target context lookup dictionary."""

    global _TARGET_XML_LOOKUP

    with open(_write_dir() / _TARGET_LOOKUP_BASENAME, 'wb') as f:
        pickle.dump(lookup, f)

    _TARGET_XML_LOOKUP = lookup


def _sort_key(basename):
    """Guarantees that basenames sort by increasing version even for x.9 -> x.10, and that
    "_local.xml" comes before ".xml".
    """

    match = _BASENAME_SPLITTER.match(basename)
    return (match.group(1), match.group(2), match.group(3), 0 if match.group(4) else 1)


##########################################################################################
# Target XML writers
##########################################################################################

def new_target_xml_dict(body_dict: dict, logger: PdsLogger | None = None) -> pathlib.Path:
    """Write a new target XML file into the cache; update the lookup.

    Returns the path to the new file.
    """

    global _PDS_TEMPLATE

    basename = f'{body_dict["lid_tail"]}_1.0_local.xml'
    logger and logger.info('Writing new target context file: ', basename)
    if _PDS_TEMPLATE is None:
        PdsTemplate.set_logger(logger or NullLogger())
        _PDS_TEMPLATE = PdsTemplate(_TEMPLATE_PATH, xml=True)

    xml_path = _write_dir() / basename
    if xml_path.exists():
        raise FileExistsError(f'File {xml_path} already exists')

    # The template refers to the body as `target`, so the dictionary is nested under that
    # key rather than passed as the top-level namespace.
    _PDS_TEMPLATE.write({'target': body_dict}, xml_path, raise_exceptions=True)
    _update_target_cache(offline=True, warn_on_duplicates=False)    # update the lookup
    return xml_path


_ALT_TITLE = re.compile(r'(.*\n)'
                        r'(\s*<Alias>\s*<alternate_title>)'
                        r'(.*?)'
                        r'(</alternate_title>\s*</Alias>\s*\n)'
                        r'(.*)', re.DOTALL)

_ALT_TITLE2 = re.compile(r'(.*?</product_class>\s*\n)'  # if Alias_List is absent
                         r'(\s*?)'
                         r'(<Modification_History>.*)', re.DOTALL)

_MOD_DETAIL = re.compile(r'(.*?\n)'
                         r'(\s*<Modification_Detail>\s*<modification_date>)'
                         r'(.*?)'
                         r'(</modification_date>\s*<version_id>)'
                         r'(\d+)\.(\d+)'
                         r'(</version_id>\s*<description>)'
                         r'(.*?)'
                         r'(\s*</description>\s*</Modification_Detail>\s*\n)'
                         r'(.*)', re.DOTALL)

_DESCRIPTION = re.compile(r'(.*\s<Target>.*\n)'
                          r'(\s*)'
                          r'<description>'
                          r'(.*)'
                          r'</description>\s*\n'
                          r'(.*)', re.DOTALL)

_VERSION_ID = re.compile(r'(.*?\n\s*<version_id>)'
                         r'(\d+)\.(\d+)'
                         r'(.*)', re.DOTALL)


def update_target_xml_dict(body_dict: dict, logger: PdsLogger | None = None):
    """Write a new local XML file with and augmented list of aliases, possibly a new
    description, and an updated modification history.

    Returns the Path to the new file.

    This function is designed to preserve the format and prior content of the existing
    file. The version number is incremented by 0.1.
    """

    # Get the current body content
    for key in [body_dict['lid_tail'], body_dict['title']] + body_dict['alt_titles']:
        xml_path = target_xml_path(key)
        if xml_path is not None:
            break

    if xml_path is None:
        raise FileNotFoundError(f'XML file not found for {body_dict["lid_tail"]}')

    content = xml_path.read_text()
    xml_dict = _read_target_xml_dict(xml_path)

    # Insert the new Aliases
    new_aliases = _missing_aliases(body_dict, xml_dict)
    if new_aliases:
        logger and logger.info(f'Inserting new aliases: {new_aliases}')
        match = _ALT_TITLE.match(content)
        if match:
            (before, temp1, last_alt_title, temp2, after) = match.groups()
            new_content = [before, temp1, last_alt_title, temp2]
            for alt in new_aliases:
                new_content += [temp1, escape(alt), temp2]
            new_content += [after]
        else:
            match = _ALT_TITLE2.match(content)
            (before, indent, after) = match.groups()
            new_content = [before, indent, '<Alias_List>\n']
            for alt in new_aliases:
                new_content += [indent, '  <Alias>\n', indent, '    <alternate_title>',
                                escape(alt), '</alternate_title>\n', indent,
                                '  </Alias>\n']
            new_content += [indent, '</Alias_List>\n', indent, after]
        content = ''.join(new_content)

    # Fill in the Target description if the body has one and the file's is absent
    new_desc = _new_desc(body_dict, xml_dict)
    if new_desc:
        match = _DESCRIPTION.match(content)
        (before, indent, old_desc, after) = match.groups()
        logger and logger.info('Inserting new description')
        new_content = [before, indent, '<description>\n']
        if old_desc.lower() not in ('', 'none', 'none.'):
            new_content += [old_desc, '\n']
        for text in body_dict['description']:
            new_content += [indent, '  ', escape(text), '\n']
        new_content += [indent, '</description>\n', after]
        content = ''.join(new_content)

    # Insert the new Modification_Detail describing exactly what changed
    parts = []
    if new_aliases:
        parts.append(f'alternate_title{"s" if len(new_aliases) > 1 else ""}')
    if new_desc:
        parts.append('description')
    change = ("RMS Node's HST pipeline added " + ' and '.join(parts) + '.' if parts
              else "Metadata update by the RMS Node's HST pipeline.")

    match = _MOD_DETAIL.match(content)
    (before, temp1, mod_date, temp2, v1, v2, temp3, desc, temp4, after) = match.groups()
    new_version = f'{v1}.{int(v2) + 1}'
    new_content = [before,
                   temp1, datetime.date.today().isoformat(),
                   temp2, new_version,
                   temp3, change,
                   temp4,
                   temp1, mod_date, temp2, v1, '.', v2, temp3, desc, temp4, after]
    content = ''.join(new_content)

    # Update the version_id
    match = _VERSION_ID.match(content)
    (before, v1, v2, after) = match.groups()
    new_content = [before, new_version, after]
    content = ''.join(new_content)

    # Write the new file into the overlay (or the committed cache when no overlay is
    # active)
    new_basename = xml_path.name.replace('_local.xml', '.xml')
    new_basename = new_basename.replace(f'{v1}.{v2}.xml', f'{new_version}_local.xml')
    new_path = _write_dir() / new_basename
    if new_path.exists():
        raise FileExistsError(f'File {new_path} already exists')

    new_path.write_text(content)
    _update_target_cache(offline=True, warn_on_duplicates=False)    # update the lookup
    return new_path


def _missing_aliases(new_body, old_body):
    """Titles of the new body that do not appear in the old body's list of titles, either
    as a string or a substring.

    Returns the list of extra names.
    """

    new_names = [new_body['title']] + new_body['alt_titles']
    old_names = set([old_body['title']] + old_body['alt_titles'])

    extras = []
    for name in new_names:
        if name in old_names:
            continue

        # Omit a name entirely inside another
        inside = False
        for test in old_names:
            if name in test:
                inside = True
                break
        if inside:
            continue

        # Omit "Minor Planet ..."
        if name.startswith('Minor Planet'):
            continue

        # Omit a name that is the same except for parentheses
        match = False
        for test in old_names:
            test = test.replace('(', '').replace(')', '')
            name2 = name.replace('(', '').replace(')', '')
            if test == name2:
                match = True
                break
        if match:
            continue

        extras.append(name)

    return extras


def _new_desc(new_body, old_body):
    """True if none of the new body's description appears in the old body's description.
    """

    if not new_body['description']:
        return False

    # Compare ignoring spaces and case
    old_desc = set(d.replace(' ', '').lower() for d in old_body['description'])

    for text in new_body['description']:
        text = text.replace(' ', '').lower()
        if text and text in old_desc:
            return False

    return True


__all__ = ['new_target_xml_dict', 'find_xml_dict', 'find_xml_path', 'target_xml_dict',
           'target_xml_lookup', 'target_xml_path', 'update_target_xml_dict',
           'use_local_xml_dir']

##########################################################################################
